import { useEffect, useMemo, useState, type ChangeEvent } from 'react';
import { debounce } from 'lodash';

import { geocode, RequestType, OutputFormat } from 'react-geocode';
import { SearchBar } from '../SearchBar';
import { DailyData } from '../DailyData';
import { CurrentData } from '../CurrentData';
import { HourlyData } from '../HourlyData';
import { skipToken, useQuery } from '@tanstack/react-query';
import { EmptyState } from '../EmptyState';
import type { ICurrentData, IHourlyData, IDailyData } from '../../types';
import { showErrorToast } from '../../utils';

export const MainPage = () => {
  const [searchText, setSearchText] = useState('');
  const [coordinates, setCoordinates] = useState({
    latitude: 54.352,
    longitude: 18.6466,
  });

  const [currentData, setCurrentData] = useState<ICurrentData | null>(null);
  const [hourlyData, setHourlyData] = useState<IHourlyData[]>([]);
  const [dailyData, setDailyData] = useState<IDailyData[]>([]);

  const { isPending } = useQuery({
    queryKey: ['weatherData', coordinates.latitude, coordinates.longitude],
    queryFn:
      coordinates.latitude && coordinates.longitude
        ? async () => {
            // const response = await fetch(
            //   `https://api.openweathermap.org/data/3.0/onecall?lat=${coordinates.latitude}&lon=${coordinates.longitude}&appid=${import.meta.env.VITE_OPENWEATHER_API_KEY}&units=metric`
            // );
            const r = {
              lat: 54.352,
              lon: 18.6466,
              timezone: 'Europe/Warsaw',
              timezone_offset: 7200,
              current: {
                dt: 1755876587,
                sunrise: 1755833702,
                sunset: 1755885718,
                temp: 17.19,
                feels_like: 16.61,
                pressure: 1008,
                humidity: 63,
                dew_point: 10.09,
                uvi: 0.89,
                clouds: 40,
                visibility: 10000,
                wind_speed: 9.26,
                wind_deg: 280,
                weather: [
                  {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                  },
                ],
              },
              minutely: [
                {
                  dt: 1755876600,
                  precipitation: 0,
                },
                {
                  dt: 1755876660,
                  precipitation: 0,
                },
                {
                  dt: 1755876720,
                  precipitation: 0,
                },
                {
                  dt: 1755876780,
                  precipitation: 0,
                },
                {
                  dt: 1755876840,
                  precipitation: 0,
                },
                {
                  dt: 1755876900,
                  precipitation: 0,
                },
                {
                  dt: 1755876960,
                  precipitation: 0,
                },
                {
                  dt: 1755877020,
                  precipitation: 0,
                },
                {
                  dt: 1755877080,
                  precipitation: 0,
                },
                {
                  dt: 1755877140,
                  precipitation: 0,
                },
                {
                  dt: 1755877200,
                  precipitation: 0,
                },
                {
                  dt: 1755877260,
                  precipitation: 0,
                },
                {
                  dt: 1755877320,
                  precipitation: 0,
                },
                {
                  dt: 1755877380,
                  precipitation: 0,
                },
                {
                  dt: 1755877440,
                  precipitation: 0,
                },
                {
                  dt: 1755877500,
                  precipitation: 0,
                },
                {
                  dt: 1755877560,
                  precipitation: 0,
                },
                {
                  dt: 1755877620,
                  precipitation: 0,
                },
                {
                  dt: 1755877680,
                  precipitation: 0.1068,
                },
                {
                  dt: 1755877740,
                  precipitation: 0.1304,
                },
                {
                  dt: 1755877800,
                  precipitation: 0.154,
                },
                {
                  dt: 1755877860,
                  precipitation: 0.4784,
                },
                {
                  dt: 1755877920,
                  precipitation: 0.8028,
                },
                {
                  dt: 1755877980,
                  precipitation: 1.1272,
                },
                {
                  dt: 1755878040,
                  precipitation: 1.4516,
                },
                {
                  dt: 1755878100,
                  precipitation: 1.776,
                },
                {
                  dt: 1755878160,
                  precipitation: 1.9676,
                },
                {
                  dt: 1755878220,
                  precipitation: 2.1592,
                },
                {
                  dt: 1755878280,
                  precipitation: 2.3508,
                },
                {
                  dt: 1755878340,
                  precipitation: 2.5424,
                },
                {
                  dt: 1755878400,
                  precipitation: 2.734,
                },
                {
                  dt: 1755878460,
                  precipitation: 2.3168,
                },
                {
                  dt: 1755878520,
                  precipitation: 1.8996,
                },
                {
                  dt: 1755878580,
                  precipitation: 1.4824,
                },
                {
                  dt: 1755878640,
                  precipitation: 1.0652,
                },
                {
                  dt: 1755878700,
                  precipitation: 0.648,
                },
                {
                  dt: 1755878760,
                  precipitation: 0.554,
                },
                {
                  dt: 1755878820,
                  precipitation: 0.46,
                },
                {
                  dt: 1755878880,
                  precipitation: 0.366,
                },
                {
                  dt: 1755878940,
                  precipitation: 0.272,
                },
                {
                  dt: 1755879000,
                  precipitation: 0.178,
                },
                {
                  dt: 1755879060,
                  precipitation: 0.2266,
                },
                {
                  dt: 1755879120,
                  precipitation: 0.2752,
                },
                {
                  dt: 1755879180,
                  precipitation: 0.3238,
                },
                {
                  dt: 1755879240,
                  precipitation: 0.3724,
                },
                {
                  dt: 1755879300,
                  precipitation: 0.421,
                },
                {
                  dt: 1755879360,
                  precipitation: 0.692,
                },
                {
                  dt: 1755879420,
                  precipitation: 0.963,
                },
                {
                  dt: 1755879480,
                  precipitation: 1.234,
                },
                {
                  dt: 1755879540,
                  precipitation: 1.505,
                },
                {
                  dt: 1755879600,
                  precipitation: 1.776,
                },
                {
                  dt: 1755879660,
                  precipitation: 1.5706,
                },
                {
                  dt: 1755879720,
                  precipitation: 1.3652,
                },
                {
                  dt: 1755879780,
                  precipitation: 1.1598,
                },
                {
                  dt: 1755879840,
                  precipitation: 0.9544,
                },
                {
                  dt: 1755879900,
                  precipitation: 0.749,
                },
                {
                  dt: 1755879960,
                  precipitation: 0.609,
                },
                {
                  dt: 1755880020,
                  precipitation: 0.469,
                },
                {
                  dt: 1755880080,
                  precipitation: 0.329,
                },
                {
                  dt: 1755880140,
                  precipitation: 0.189,
                },
              ],
              hourly: [
                {
                  dt: 1755874800,
                  temp: 17.19,
                  feels_like: 16.61,
                  pressure: 1008,
                  humidity: 63,
                  dew_point: 10.09,
                  uvi: 0.89,
                  clouds: 40,
                  visibility: 10000,
                  wind_speed: 7.99,
                  wind_deg: 280,
                  wind_gust: 10.83,
                  weather: [
                    {
                      id: 802,
                      main: 'Clouds',
                      description: 'scattered clouds',
                      icon: '03d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755878400,
                  temp: 17.31,
                  feels_like: 16.72,
                  pressure: 1008,
                  humidity: 62,
                  dew_point: 9.97,
                  uvi: 0.13,
                  clouds: 46,
                  visibility: 10000,
                  wind_speed: 7.98,
                  wind_deg: 278,
                  wind_gust: 11.08,
                  weather: [
                    {
                      id: 501,
                      main: 'Rain',
                      description: 'moderate rain',
                      icon: '10d',
                    },
                  ],
                  pop: 0.2,
                  rain: {
                    '1h': 2.73,
                  },
                },
                {
                  dt: 1755882000,
                  temp: 17.27,
                  feels_like: 16.65,
                  pressure: 1008,
                  humidity: 61,
                  dew_point: 9.69,
                  uvi: 0.13,
                  clouds: 52,
                  visibility: 10000,
                  wind_speed: 7.32,
                  wind_deg: 270,
                  wind_gust: 11.71,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755885600,
                  temp: 16.21,
                  feels_like: 15.56,
                  pressure: 1008,
                  humidity: 64,
                  dew_point: 9.4,
                  uvi: 0,
                  clouds: 53,
                  visibility: 10000,
                  wind_speed: 6.64,
                  wind_deg: 266,
                  wind_gust: 11.2,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755889200,
                  temp: 14.28,
                  feels_like: 13.51,
                  pressure: 1008,
                  humidity: 67,
                  dew_point: 8.24,
                  uvi: 0,
                  clouds: 10,
                  visibility: 10000,
                  wind_speed: 6.4,
                  wind_deg: 259,
                  wind_gust: 12.73,
                  weather: [
                    {
                      id: 800,
                      main: 'Clear',
                      description: 'clear sky',
                      icon: '01n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755892800,
                  temp: 12.7,
                  feels_like: 11.8,
                  pressure: 1008,
                  humidity: 68,
                  dew_point: 8.16,
                  uvi: 0,
                  clouds: 4,
                  visibility: 10000,
                  wind_speed: 6.8,
                  wind_deg: 255,
                  wind_gust: 13.3,
                  weather: [
                    {
                      id: 800,
                      main: 'Clear',
                      description: 'clear sky',
                      icon: '01n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755896400,
                  temp: 12.85,
                  feels_like: 12.04,
                  pressure: 1008,
                  humidity: 71,
                  dew_point: 8.11,
                  uvi: 0,
                  clouds: 2,
                  visibility: 10000,
                  wind_speed: 6.86,
                  wind_deg: 255,
                  wind_gust: 12.51,
                  weather: [
                    {
                      id: 800,
                      main: 'Clear',
                      description: 'clear sky',
                      icon: '01n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755900000,
                  temp: 13.3,
                  feels_like: 12.49,
                  pressure: 1008,
                  humidity: 69,
                  dew_point: 7.73,
                  uvi: 0,
                  clouds: 7,
                  visibility: 10000,
                  wind_speed: 6.36,
                  wind_deg: 253,
                  wind_gust: 11.54,
                  weather: [
                    {
                      id: 800,
                      main: 'Clear',
                      description: 'clear sky',
                      icon: '01n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755903600,
                  temp: 12.81,
                  feels_like: 11.9,
                  pressure: 1008,
                  humidity: 67,
                  dew_point: 7.66,
                  uvi: 0,
                  clouds: 20,
                  visibility: 10000,
                  wind_speed: 5.25,
                  wind_deg: 270,
                  wind_gust: 9.75,
                  weather: [
                    {
                      id: 801,
                      main: 'Clouds',
                      description: 'few clouds',
                      icon: '02n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755907200,
                  temp: 13.01,
                  feels_like: 12.09,
                  pressure: 1008,
                  humidity: 66,
                  dew_point: 7.23,
                  uvi: 0,
                  clouds: 27,
                  visibility: 10000,
                  wind_speed: 4.19,
                  wind_deg: 275,
                  wind_gust: 6.93,
                  weather: [
                    {
                      id: 802,
                      main: 'Clouds',
                      description: 'scattered clouds',
                      icon: '03n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1755910800,
                  temp: 12.42,
                  feels_like: 11.62,
                  pressure: 1008,
                  humidity: 73,
                  dew_point: 7.46,
                  uvi: 0,
                  clouds: 62,
                  visibility: 10000,
                  wind_speed: 3.76,
                  wind_deg: 266,
                  wind_gust: 6.03,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10n',
                    },
                  ],
                  pop: 0.36,
                  rain: {
                    '1h': 0.1,
                  },
                },
                {
                  dt: 1755914400,
                  temp: 11.75,
                  feels_like: 11.02,
                  pressure: 1008,
                  humidity: 78,
                  dew_point: 7.49,
                  uvi: 0,
                  clouds: 64,
                  visibility: 10000,
                  wind_speed: 3.35,
                  wind_deg: 261,
                  wind_gust: 5.3,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.08,
                },
                {
                  dt: 1755918000,
                  temp: 11.47,
                  feels_like: 10.76,
                  pressure: 1007,
                  humidity: 80,
                  dew_point: 7.63,
                  uvi: 0,
                  clouds: 73,
                  visibility: 10000,
                  wind_speed: 3.27,
                  wind_deg: 257,
                  wind_gust: 5.39,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.07,
                },
                {
                  dt: 1755921600,
                  temp: 12.19,
                  feels_like: 11.53,
                  pressure: 1007,
                  humidity: 79,
                  dew_point: 7.66,
                  uvi: 0,
                  clouds: 79,
                  visibility: 10000,
                  wind_speed: 3.42,
                  wind_deg: 250,
                  wind_gust: 6.35,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.07,
                },
                {
                  dt: 1755925200,
                  temp: 13.72,
                  feels_like: 13.13,
                  pressure: 1007,
                  humidity: 76,
                  dew_point: 8.12,
                  uvi: 0.25,
                  clouds: 83,
                  visibility: 10000,
                  wind_speed: 4.47,
                  wind_deg: 256,
                  wind_gust: 7.8,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.08,
                },
                {
                  dt: 1755928800,
                  temp: 14.72,
                  feels_like: 14.02,
                  pressure: 1007,
                  humidity: 68,
                  dew_point: 8.08,
                  uvi: 0.69,
                  clouds: 86,
                  visibility: 10000,
                  wind_speed: 5.39,
                  wind_deg: 261,
                  wind_gust: 7.85,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.08,
                },
                {
                  dt: 1755932400,
                  temp: 14.75,
                  feels_like: 13.87,
                  pressure: 1007,
                  humidity: 61,
                  dew_point: 7.47,
                  uvi: 1.38,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.85,
                  wind_deg: 266,
                  wind_gust: 7.39,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 0.52,
                  rain: {
                    '1h': 0.16,
                  },
                },
                {
                  dt: 1755936000,
                  temp: 15.8,
                  feels_like: 14.87,
                  pressure: 1008,
                  humidity: 55,
                  dew_point: 6.66,
                  uvi: 2.03,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.49,
                  wind_deg: 272,
                  wind_gust: 6.37,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.47,
                },
                {
                  dt: 1755939600,
                  temp: 16.06,
                  feels_like: 15.11,
                  pressure: 1008,
                  humidity: 53,
                  dew_point: 6.48,
                  uvi: 1.55,
                  clouds: 99,
                  visibility: 10000,
                  wind_speed: 4.89,
                  wind_deg: 279,
                  wind_gust: 5.7,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 0.99,
                  rain: {
                    '1h': 0.2,
                  },
                },
                {
                  dt: 1755943200,
                  temp: 15.48,
                  feels_like: 14.55,
                  pressure: 1008,
                  humidity: 56,
                  dew_point: 6.79,
                  uvi: 2.82,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.22,
                  wind_deg: 273,
                  wind_gust: 5.45,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 1,
                  rain: {
                    '1h': 0.33,
                  },
                },
                {
                  dt: 1755946800,
                  temp: 13.57,
                  feels_like: 12.81,
                  pressure: 1008,
                  humidity: 70,
                  dew_point: 7.98,
                  uvi: 1.77,
                  clouds: 100,
                  visibility: 6804,
                  wind_speed: 5.92,
                  wind_deg: 259,
                  wind_gust: 7.73,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 1,
                  rain: {
                    '1h': 0.78,
                  },
                },
                {
                  dt: 1755950400,
                  temp: 13.54,
                  feels_like: 12.75,
                  pressure: 1008,
                  humidity: 69,
                  dew_point: 7.57,
                  uvi: 2.17,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 3.83,
                  wind_deg: 266,
                  wind_gust: 6.6,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 1,
                  rain: {
                    '1h': 0.73,
                  },
                },
                {
                  dt: 1755954000,
                  temp: 14.08,
                  feels_like: 13.21,
                  pressure: 1008,
                  humidity: 64,
                  dew_point: 7.29,
                  uvi: 0.92,
                  clouds: 99,
                  visibility: 10000,
                  wind_speed: 4.57,
                  wind_deg: 287,
                  wind_gust: 6.75,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 1,
                  rain: {
                    '1h': 0.43,
                  },
                },
                {
                  dt: 1755957600,
                  temp: 13.07,
                  feels_like: 12.29,
                  pressure: 1008,
                  humidity: 71,
                  dew_point: 7.63,
                  uvi: 0.44,
                  clouds: 99,
                  visibility: 10000,
                  wind_speed: 4.6,
                  wind_deg: 284,
                  wind_gust: 8.31,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  pop: 1,
                  rain: {
                    '1h': 0.37,
                  },
                },
                {
                  dt: 1755961200,
                  temp: 14.2,
                  feels_like: 13.29,
                  pressure: 1009,
                  humidity: 62,
                  dew_point: 6.91,
                  uvi: 0.28,
                  clouds: 99,
                  visibility: 10000,
                  wind_speed: 5.06,
                  wind_deg: 317,
                  wind_gust: 7.99,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.8,
                },
                {
                  dt: 1755964800,
                  temp: 14.48,
                  feels_like: 13.47,
                  pressure: 1009,
                  humidity: 57,
                  dew_point: 6.18,
                  uvi: 0.1,
                  clouds: 99,
                  visibility: 10000,
                  wind_speed: 5.49,
                  wind_deg: 334,
                  wind_gust: 7.15,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.71,
                },
                {
                  dt: 1755968400,
                  temp: 13.84,
                  feels_like: 12.79,
                  pressure: 1009,
                  humidity: 58,
                  dew_point: 5.78,
                  uvi: 0.03,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 4.69,
                  wind_deg: 329,
                  wind_gust: 6.74,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0.8,
                },
                {
                  dt: 1755972000,
                  temp: 12.07,
                  feels_like: 11.03,
                  pressure: 1010,
                  humidity: 65,
                  dew_point: 5.7,
                  uvi: 0,
                  clouds: 91,
                  visibility: 10000,
                  wind_speed: 4.9,
                  wind_deg: 315,
                  wind_gust: 6.45,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.74,
                },
                {
                  dt: 1755975600,
                  temp: 11.36,
                  feels_like: 10.43,
                  pressure: 1010,
                  humidity: 72,
                  dew_point: 6.47,
                  uvi: 0,
                  clouds: 47,
                  visibility: 10000,
                  wind_speed: 4.97,
                  wind_deg: 309,
                  wind_gust: 8.39,
                  weather: [
                    {
                      id: 802,
                      main: 'Clouds',
                      description: 'scattered clouds',
                      icon: '03n',
                    },
                  ],
                  pop: 0.13,
                },
                {
                  dt: 1755979200,
                  temp: 10.8,
                  feels_like: 9.89,
                  pressure: 1011,
                  humidity: 75,
                  dew_point: 6.46,
                  uvi: 0,
                  clouds: 44,
                  visibility: 10000,
                  wind_speed: 3.57,
                  wind_deg: 317,
                  wind_gust: 7.79,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10n',
                    },
                  ],
                  pop: 0.62,
                  rain: {
                    '1h': 0.35,
                  },
                },
                {
                  dt: 1755982800,
                  temp: 11.24,
                  feels_like: 10.4,
                  pressure: 1011,
                  humidity: 76,
                  dew_point: 7.09,
                  uvi: 0,
                  clouds: 63,
                  visibility: 10000,
                  wind_speed: 3.35,
                  wind_deg: 274,
                  wind_gust: 5,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10n',
                    },
                  ],
                  pop: 0.64,
                  rain: {
                    '1h': 0.28,
                  },
                },
                {
                  dt: 1755986400,
                  temp: 10.45,
                  feels_like: 9.54,
                  pressure: 1011,
                  humidity: 76,
                  dew_point: 6.24,
                  uvi: 0,
                  clouds: 68,
                  visibility: 10000,
                  wind_speed: 3.78,
                  wind_deg: 282,
                  wind_gust: 6.92,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.57,
                },
                {
                  dt: 1755990000,
                  temp: 10.18,
                  feels_like: 9.19,
                  pressure: 1011,
                  humidity: 74,
                  dew_point: 5.61,
                  uvi: 0,
                  clouds: 72,
                  visibility: 10000,
                  wind_speed: 3.91,
                  wind_deg: 279,
                  wind_gust: 7.01,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.52,
                },
                {
                  dt: 1755993600,
                  temp: 10.15,
                  feels_like: 9.13,
                  pressure: 1011,
                  humidity: 73,
                  dew_point: 5.49,
                  uvi: 0,
                  clouds: 77,
                  visibility: 10000,
                  wind_speed: 4.49,
                  wind_deg: 273,
                  wind_gust: 8.92,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0.49,
                },
                {
                  dt: 1755997200,
                  temp: 11.19,
                  feels_like: 10.24,
                  pressure: 1011,
                  humidity: 72,
                  dew_point: 6.1,
                  uvi: 0,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.28,
                  wind_deg: 274,
                  wind_gust: 10.87,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756000800,
                  temp: 11.34,
                  feels_like: 10.41,
                  pressure: 1011,
                  humidity: 72,
                  dew_point: 6.49,
                  uvi: 0,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 6.02,
                  wind_deg: 267,
                  wind_gust: 11.09,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756004400,
                  temp: 11.19,
                  feels_like: 10.27,
                  pressure: 1011,
                  humidity: 73,
                  dew_point: 6.58,
                  uvi: 0,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.99,
                  wind_deg: 280,
                  wind_gust: 11.59,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04n',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756008000,
                  temp: 11.66,
                  feels_like: 10.68,
                  pressure: 1011,
                  humidity: 69,
                  dew_point: 6.15,
                  uvi: 0,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 5.51,
                  wind_deg: 281,
                  wind_gust: 11.63,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756011600,
                  temp: 12.82,
                  feels_like: 11.88,
                  pressure: 1012,
                  humidity: 66,
                  dew_point: 6.55,
                  uvi: 0.23,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 6.03,
                  wind_deg: 291,
                  wind_gust: 11.89,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756015200,
                  temp: 14.2,
                  feels_like: 13.29,
                  pressure: 1012,
                  humidity: 62,
                  dew_point: 7.03,
                  uvi: 0.59,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 6.16,
                  wind_deg: 295,
                  wind_gust: 10.95,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756018800,
                  temp: 16.2,
                  feels_like: 15.31,
                  pressure: 1012,
                  humidity: 55,
                  dew_point: 7.13,
                  uvi: 1.52,
                  clouds: 100,
                  visibility: 10000,
                  wind_speed: 7.37,
                  wind_deg: 299,
                  wind_gust: 10.8,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756022400,
                  temp: 16.98,
                  feels_like: 16.04,
                  pressure: 1012,
                  humidity: 50,
                  dew_point: 6.62,
                  uvi: 2.46,
                  clouds: 89,
                  visibility: 10000,
                  wind_speed: 8.18,
                  wind_deg: 302,
                  wind_gust: 10.47,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756026000,
                  temp: 17.65,
                  feels_like: 16.72,
                  pressure: 1013,
                  humidity: 48,
                  dew_point: 6.51,
                  uvi: 3.33,
                  clouds: 86,
                  visibility: 10000,
                  wind_speed: 7.67,
                  wind_deg: 302,
                  wind_gust: 9.54,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756029600,
                  temp: 18.31,
                  feels_like: 17.37,
                  pressure: 1013,
                  humidity: 45,
                  dew_point: 6.1,
                  uvi: 4.03,
                  clouds: 84,
                  visibility: 10000,
                  wind_speed: 7.28,
                  wind_deg: 300,
                  wind_gust: 8.9,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756033200,
                  temp: 18.04,
                  feels_like: 17.02,
                  pressure: 1012,
                  humidity: 43,
                  dew_point: 5.41,
                  uvi: 4.18,
                  clouds: 85,
                  visibility: 10000,
                  wind_speed: 6.78,
                  wind_deg: 298,
                  wind_gust: 8.73,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756036800,
                  temp: 18.15,
                  feels_like: 17.12,
                  pressure: 1012,
                  humidity: 42,
                  dew_point: 4.9,
                  uvi: 3.92,
                  clouds: 89,
                  visibility: 10000,
                  wind_speed: 7.07,
                  wind_deg: 294,
                  wind_gust: 8.73,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756040400,
                  temp: 18.91,
                  feels_like: 17.85,
                  pressure: 1012,
                  humidity: 38,
                  dew_point: 4.15,
                  uvi: 3.09,
                  clouds: 96,
                  visibility: 10000,
                  wind_speed: 7.49,
                  wind_deg: 295,
                  wind_gust: 9.51,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
                {
                  dt: 1756044000,
                  temp: 19.22,
                  feels_like: 18.27,
                  pressure: 1012,
                  humidity: 41,
                  dew_point: 5.78,
                  uvi: 1.8,
                  clouds: 86,
                  visibility: 10000,
                  wind_speed: 7.7,
                  wind_deg: 297,
                  wind_gust: 10.37,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  pop: 0,
                },
              ],
              daily: [
                {
                  dt: 1755856800,
                  sunrise: 1755833702,
                  sunset: 1755885718,
                  moonrise: 1755828120,
                  moonset: 1755885540,
                  moon_phase: 0.97,
                  summary: 'Expect a day of partly cloudy with rain',
                  temp: {
                    day: 19.13,
                    min: 11.45,
                    max: 19.13,
                    night: 12.85,
                    eve: 17.31,
                    morn: 11.76,
                  },
                  feels_like: {
                    day: 18.61,
                    night: 12.04,
                    eve: 16.72,
                    morn: 11.13,
                  },
                  pressure: 1007,
                  humidity: 58,
                  dew_point: 7,
                  wind_speed: 7.99,
                  wind_deg: 280,
                  wind_gust: 13.3,
                  weather: [
                    {
                      id: 501,
                      main: 'Rain',
                      description: 'moderate rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 39,
                  pop: 0.57,
                  rain: 2.73,
                  uvi: 3.51,
                },
                {
                  dt: 1755943200,
                  sunrise: 1755920211,
                  sunset: 1755971979,
                  moonrise: 1755919740,
                  moonset: 1755972480,
                  moon_phase: 0,
                  summary: 'Expect a day of partly cloudy with rain',
                  temp: {
                    day: 15.48,
                    min: 10.8,
                    max: 16.06,
                    night: 11.24,
                    eve: 14.48,
                    morn: 12.19,
                  },
                  feels_like: {
                    day: 14.55,
                    night: 10.4,
                    eve: 13.47,
                    morn: 11.53,
                  },
                  pressure: 1008,
                  humidity: 56,
                  dew_point: 6.79,
                  wind_speed: 6.36,
                  wind_deg: 253,
                  wind_gust: 11.54,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 100,
                  pop: 1,
                  rain: 3.73,
                  uvi: 2.82,
                },
                {
                  dt: 1756029600,
                  sunrise: 1756006720,
                  sunset: 1756058238,
                  moonrise: 1756011060,
                  moonset: 1756059300,
                  moon_phase: 0.04,
                  summary: 'Expect a day of partly cloudy with clear spells',
                  temp: {
                    day: 18.31,
                    min: 10.15,
                    max: 19.22,
                    night: 12.74,
                    eve: 17.46,
                    morn: 11.66,
                  },
                  feels_like: {
                    day: 17.37,
                    night: 11.95,
                    eve: 16.67,
                    morn: 10.68,
                  },
                  pressure: 1013,
                  humidity: 45,
                  dew_point: 6.1,
                  wind_speed: 8.18,
                  wind_deg: 302,
                  wind_gust: 12.22,
                  weather: [
                    {
                      id: 803,
                      main: 'Clouds',
                      description: 'broken clouds',
                      icon: '04d',
                    },
                  ],
                  clouds: 84,
                  pop: 0.57,
                  uvi: 4.18,
                },
                {
                  dt: 1756116000,
                  sunrise: 1756093229,
                  sunset: 1756144497,
                  moonrise: 1756102140,
                  moonset: 1756146120,
                  moon_phase: 0.07,
                  summary: 'Expect a day of partly cloudy with rain',
                  temp: {
                    day: 18.97,
                    min: 11.56,
                    max: 19.5,
                    night: 11.56,
                    eve: 16.14,
                    morn: 12.58,
                  },
                  feels_like: {
                    day: 18.2,
                    night: 10.81,
                    eve: 15.43,
                    morn: 12.03,
                  },
                  pressure: 1011,
                  humidity: 49,
                  dew_point: 8.1,
                  wind_speed: 6.9,
                  wind_deg: 327,
                  wind_gust: 12.17,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 74,
                  pop: 1,
                  rain: 0.4,
                  uvi: 3.97,
                },
                {
                  dt: 1756202400,
                  sunrise: 1756179739,
                  sunset: 1756230755,
                  moonrise: 1756193160,
                  moonset: 1756232880,
                  moon_phase: 0.1,
                  summary: 'Expect a day of partly cloudy with rain',
                  temp: {
                    day: 18.1,
                    min: 10.88,
                    max: 19.36,
                    night: 12.28,
                    eve: 18.15,
                    morn: 10.88,
                  },
                  feels_like: {
                    day: 17.38,
                    night: 11.5,
                    eve: 17.17,
                    morn: 10.35,
                  },
                  pressure: 1010,
                  humidity: 54,
                  dew_point: 8.78,
                  wind_speed: 5.27,
                  wind_deg: 265,
                  wind_gust: 6.45,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 99,
                  pop: 0.59,
                  rain: 1.38,
                  uvi: 4.42,
                },
                {
                  dt: 1756288800,
                  sunrise: 1756266248,
                  sunset: 1756317012,
                  moonrise: 1756284120,
                  moonset: 1756319760,
                  moon_phase: 0.13,
                  summary:
                    'There will be clear sky until morning, then partly cloudy',
                  temp: {
                    day: 17.52,
                    min: 11.24,
                    max: 18.78,
                    night: 14.4,
                    eve: 17.41,
                    morn: 11.24,
                  },
                  feels_like: {
                    day: 16.69,
                    night: 13.8,
                    eve: 16.72,
                    morn: 10.48,
                  },
                  pressure: 1014,
                  humidity: 52,
                  dew_point: 7.47,
                  wind_speed: 5.19,
                  wind_deg: 36,
                  wind_gust: 5.37,
                  weather: [
                    {
                      id: 804,
                      main: 'Clouds',
                      description: 'overcast clouds',
                      icon: '04d',
                    },
                  ],
                  clouds: 100,
                  pop: 0,
                  uvi: 5,
                },
                {
                  dt: 1756375200,
                  sunrise: 1756352756,
                  sunset: 1756403268,
                  moonrise: 1756375140,
                  moonset: 1756406700,
                  moon_phase: 0.16,
                  summary:
                    'You can expect partly cloudy in the morning, with rain in the afternoon',
                  temp: {
                    day: 15.7,
                    min: 13.57,
                    max: 18.42,
                    night: 14.11,
                    eve: 18.42,
                    morn: 13.64,
                  },
                  feels_like: {
                    day: 15,
                    night: 13.53,
                    eve: 17.68,
                    morn: 13.07,
                  },
                  pressure: 1013,
                  humidity: 64,
                  dew_point: 9,
                  wind_speed: 6.81,
                  wind_deg: 91,
                  wind_gust: 10.95,
                  weather: [
                    {
                      id: 500,
                      main: 'Rain',
                      description: 'light rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 100,
                  pop: 1,
                  rain: 0.78,
                  uvi: 5,
                },
                {
                  dt: 1756461600,
                  sunrise: 1756439265,
                  sunset: 1756489524,
                  moonrise: 1756466220,
                  moonset: 1756493880,
                  moon_phase: 0.19,
                  summary: 'Expect a day of partly cloudy with rain',
                  temp: {
                    day: 18.5,
                    min: 12.91,
                    max: 20.7,
                    night: 16.31,
                    eve: 20.2,
                    morn: 12.91,
                  },
                  feels_like: {
                    day: 18.36,
                    night: 16.4,
                    eve: 20.08,
                    morn: 12.63,
                  },
                  pressure: 1003,
                  humidity: 75,
                  dew_point: 13.92,
                  wind_speed: 5.7,
                  wind_deg: 101,
                  wind_gust: 10.12,
                  weather: [
                    {
                      id: 501,
                      main: 'Rain',
                      description: 'moderate rain',
                      icon: '10d',
                    },
                  ],
                  clouds: 100,
                  pop: 1,
                  rain: 6.93,
                  uvi: 5,
                },
              ],
            };
            setCurrentData(r.current);
            setHourlyData(r.hourly);
            setDailyData(r.daily);
            return r;
          }
        : skipToken,
  });

  const handleSearchTextChange = (e: ChangeEvent<HTMLInputElement>) =>
    setSearchText(e.target.value);

  const debouncedHandleSearchTextChange = useMemo(
    () =>
      debounce(
        (e: ChangeEvent<HTMLInputElement>) => handleSearchTextChange(e),
        1000
      ),
    []
  );

  useEffect(() => {
    return () => debouncedHandleSearchTextChange.cancel();
  }, []);

  useEffect(() => {
    if (!searchText) return;
    geocode(RequestType.ADDRESS, searchText, {
      key: import.meta.env.VITE_GEOCODING_API_KEY,
      outputFormat: OutputFormat.JSON,
    })
      .then((response) => {
        if (!response.results.length || response.status === 'ZERO_RESULTS') {
          showErrorToast('Please provide an existing address');
          return;
        }
        const { lat, lng } = response.results[0].geometry.location;
        setCoordinates({
          ...coordinates,
          latitude: Number(lat),
          longitude: Number(lng),
        });
      })
      .catch(() => {
        showErrorToast('Please provide an existing address');
      });
  }, [searchText]);

  return (
    <div className="px-40 py-10 w-dvw h-dvh overflow-y-clip">
      <SearchBar handleSearchTextChange={debouncedHandleSearchTextChange} />
      {isPending ? (
        <EmptyState />
      ) : (
        <div className="flex flex-row">
          <div className="w-[70%] pr-16">
            {currentData && <CurrentData currentData={currentData} />}
            <HourlyData hourlyData={hourlyData} />
          </div>
          <div className="w-50">
            <DailyData dailyData={dailyData} />
          </div>
        </div>
      )}
    </div>
  );
};
